# Site settings
title: Robin Ricard
email: pro@rricard.me
description: ""
baseurl: ""
url: "http://www.rricard.me"
twitter_username: r_ricard
github_username:  rricard

# Build settings
markdown: kramdown
